server:
  shutdown: graceful

management:
  server:
    port: ${APP_MANAGEMENT_PORT:8082}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: ${APP_TRACING_SAMPLING_PROBABILITY:0.1}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    cookie:
      csrf:
        secure: true
      access-token:
        secure: true
      refresh-token:
        secure: true
      oauth-state:
        secure: true
