services:
  identity:
    build:
      context: .
      dockerfile: services/identity-api/Dockerfile
    container_name: identity_app
    env_file:
      - .env
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE_PORT: "5432"
      APP_REDIS_HOST: redis
      APP_REDIS_PORT: "6379"
      APP_RABBITMQ_HOST: rabbitmq
      APP_RABBITMQ_PORT: "5672"
    ports:
      - "8080:8080"
    networks:
      - identity-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgres:18-alpine
    container_name: identity_db
    ports:
      - "${APP_DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"",
      ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - database-data:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - identity-network
  redis:
    image: redis:7-alpine
    container_name: identity-redis
    ports:
      - "${APP_REDIS_PORT}:6379"
    environment:
      - APP_REDIS_PASSWORD=${APP_REDIS_PASSWORD:?APP_REDIS_PASSWORD is required}
    command: >
      sh -c "exec redis-server --appendonly yes --requirepass \"$$APP_REDIS_PASSWORD\""
    volumes:
      - redis-data:/data
    networks:
      - identity-network
    healthcheck:
      test: [
        "CMD-SHELL",
        "redis-cli -a \"$${APP_REDIS_PASSWORD}\" ping | grep -q PONG",
      ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4.2.3-management
    container_name: identity_rabbitmq
    ports:
      - "${APP_RABBITMQ_PORT}:5672"
      - "${APP_RABBITMQ_CLIENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${APP_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${APP_RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - identity-network
    restart: unless-stopped
networks:
  identity-network:
    driver: bridge

volumes:
  database-data:
  redis-data:
