server:
  port: 8081

logging:
  structured:
    format: json

management:
  tracing:
    export:
      otlp:
        enabled: true
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: audit-worker
  rabbitmq:
    host: ${APP_RABBITMQ_HOST}
    port: ${APP_RABBITMQ_PORT}
    username: ${APP_RABBITMQ_USER}
    password: ${APP_RABBITMQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: auto