server:
  port: 8081

management:
  tracing:
    export:
      otlp:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: audit-worker
  data:
    redis:
      host: ${APP_REDIS_HOST}
      port: ${APP_REDIS_PORT}
      password: ${APP_REDIS_PASSWORD}
  rabbitmq:
    host: ${APP_RABBITMQ_HOST}
    port: ${APP_RABBITMQ_PORT}
    username: ${APP_RABBITMQ_USER}
    password: ${APP_RABBITMQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: false